outerPushFitR = 15.3/2;
innerR = 6.2/2;

coneRes = 3;

M6socketHeadZ = 0;  //set to '6' to create a socket for the cap head
M6socketHeadR = 10.2/2;

centerRidgeCount = 12;
edgeRidgeCount = 16;
ridgeR = 0.5;


recessDim = 6;
nutAndWasher = 8;
edgeH = 27 - recessDim - nutAndWasher; 
centerH = 48 - edgeH + M6socketHeadZ;
centerConeH = 5;
edgeConeH = 2;

//edge barrel: 27mm long by 15.8 (inner) diameter